### ISSUE TITLE
Texture is empty when changing url to a video with the same size

### ISSUE THREAD

**Issue by sebllll** [vvvv/VL.MediaFoundation#3]
**repro:**
- prepare 2 different videos with the same size
- create a videplayer node
- connect one of the 2 videos to the url pin
- switch to the second one

in that case, the output texture is empty, because invalidated was never true.

> can be fixed by either changing to another url with a different size or changing the texturewidth/textureheight pin to something different. then invalidated is set to true and the rendertarget gets created again.

**proposed fix:**
add invalidated = true; when the url changes
``` csharp
public string Url
{
    set
    {
        if (value != url)
        {
            url = value;
            engine.Source = value;
            invalidated = true;
        }
    }
}

**Comment by sebllll** [comment]
hm, i was wrong, invalidate is also happening in this case here
https://github.com/vvvv/VL.MediaFoundation/blob/ad991eef77253ef9c67add5ee62fd95d039da847/src/VideoPlayer.cs#L78

**Comment by azeno** [comment]
I do remember feeding it a wrong path/url it wouldn't recover anymore. But that's not what you describe.

**Comment by sebllll** [comment]
nope, see this patch for repro and hacky workaround:

[VideoPlayerBug.zip](https://github.com/vvvv/VL.MediaFoundation/files/5608655/VideoPlayerBug.zip)

**Comment by azeno** [comment]
[0.2.1-stride](https://www.nuget.org/packages/VL.MediaFoundation/0.2.1-stride) should fix this.
